version: '3.1'

services:
  blur: 
    image: ghcr.io/ljetina/blur:latest
    restart: unless-stopped
    env_file:
      - ../.env  # loading environment variables from the .env file for 'blur' service
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    depends_on:
      - blur
    networks:
      - app-network

  db:
    image: postgres   
    restart: always
    env_file:
      - ../.env.db  # loading POSTGRES_USER and POSTGRES_PASSWORD from .env.db
    volumes:
      - /mnt/db:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

networks:
  app-network:
    driver: bridge