version: '3'
services:
  app:
    image: ghcr.io/bartolkaruza/node-app:latest
    restart: unless-stopped
    environment:
      NODE_ENV: production
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: ankane/pgvector:v0.5.1
    env_file:
      - db_password.txt
    volumes:
      - /mnt/db:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge